### ISSUE TITLE
Add option to set Service title, text from React Native

### ISSUE THREAD

**Issue by jdegger** [X-Guard/react-native-flic2#11]

**Comment by LucasMonteiro1** [comment]
Any solution to fix this?

**Comment by jdegger** [comment]
We added this issue as an backlog item for feature implantation. At the moment the service will take over the title and icon of the parent app proces. 

Check out my latest PR which removes the old code to change the notification. We will add an api for this in a future version.

**Comment by LucasMonteiro1** [comment]
Ok, thanks @jdegger!

**Comment by jdegger** [comment]
This issue has been resolved in #19
