### ISSUE TITLE
Hide Android Service when no buttons are paired

### ISSUE THREAD

**Issue by LucasMonteiro1** [X-Guard/react-native-flic2#15]
I would like to not show the notification or only if the button is connected, is it possible?

**Comment by jdegger** [comment]
The Android notification is bound to a long running service, required to detect the button. 

We have a plan to only run the service maybe if there are more than one buttons paired with the phone. It won't be possible to only show the notification when the button is actually connected.

Are you looking for hiding the service notification when there are no buttons paired with the phone or when no button connection is active?

The first is possible, the second is not.

**Comment by LucasMonteiro1** [comment]
I want to hide the service notification when there are no buttons paired with the phone

**Comment by jdegger** [comment]
Yes, we understand your request, we also looked into it before but have not come around to creating it yet. I changed the title of the issue to better fit the problem and we might implement it later.

Of course, PRs are also very welcome (from anybody!)

**Comment by jdegger** [comment]
This issue has been resolved in #19
