### ISSUE TITLE
Unable to build app after npm installation

### ISSUE THREAD

**Issue by Dellybro** [X-Guard/react-native-flic2#16]
After I npm install, and pod install (I've also linked) i get the following error

 ignoring file /Users/Dellybro/Desktop/Zinkn/Zinkn/node_modules/react-native-flic2/ios/Frameworks/flic2lib.framework/flic2lib, missing required architecture x86_64 in file /Users/Dellybro/Desktop/Zinkn/Zinkn/node_modules/react-native-flic2/ios/Frameworks/flic2lib.framework/flic2lib (2 slices)
Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_FLICManager", referenced from:
      objc-class-ref in libreact-native-flic2.a(Flic2.o)

**Comment by jdegger** [comment]
I guess you're trying to run it in the iOS simulator? 

The flic iOS SDK does not come with simulator support by default. Head over the the iOS sdk repository from Flic to read how you can enable this. 

By default, we only support running physical devices.

**Comment by Dellybro** [comment]
@jdegger ok, and even with rn greater then 0.60 i still need to link? Or is the link in readme obsolete?

**Comment by jdegger** [comment]
You indeed don't need to link. the readme is a bit outdated. I will plan to update the example and readme soon as there is some incorrect information.

**Comment by Dellybro** [comment]
@jdegger , i appreciate you responding so fast as the project im working on is in a time crunch.

One more question, do i need to follow the directions for flic2lib by dragging the lib into project for ios and adding a dependency call for android? Or is this all done via the npm package? All i need to do is install and pod install and thats it

**Comment by jdegger** [comment]
No worries, happy to help. 

Iirc the libraries are included. It's been a while since I installed it so I'm not fully sure and currently typing this from my phone. The example app might also shine some light on this. 

It should be noted that the example and readme are slightly outdated. Some functions were removed in the last update (like startService). If it does not exist anymore, you just don't need it.

**Comment by Dellybro** [comment]
@jdegger i still seem to be getting the same error even after running it on a physical device. 

My current steps are

- npm install react-native-flic2 --save
- cd ios && pod install
- open xcode, click my device, and run

but i still seem to get the following error

`ignoring file /Users/Dellybro/Desktop/Zinkn/Zinkn/node_modules/react-native-flic2/ios/Frameworks/flic2lib.framework/flic2lib, missing required architecture x86_64 in file /Users/Dellybro/Desktop/Zinkn/Zinkn/node_modules/react-native-flic2/ios/Frameworks/flic2lib.framework/flic2lib (2 slices)`

**Comment by jdegger** [comment]
Make sure that x86_64 is not included in your project build architecture for both debug and release builds. Phones don't run on x86 so you can safely omit it. That should do the trick.

**Comment by Dellybro** [comment]
@jdegger once again i appreciate the help.

I've added it the excluded architecture. Is this good enough or where exactly were you telling me to omit the architecture?

![Screen Shot 2020-11-10 at 10 01 09 AM](https://user-images.githubusercontent.com/10732096/98706091-a993a400-233b-11eb-91b6-d4c2c0fa5f64.png)

**Comment by jdegger** [comment]
Yes that might be it. Not completely sure to be honest but I guess just try 👍

**Comment by Dellybro** [comment]
Alright it worked! @jdegger thank you so much!

**Comment by jdegger** [comment]
Great, good luck 👍
