### ISSUE TITLE
Flic2 not initiliazing

### ISSUE THREAD

**Issue by Dellybro** [X-Guard/react-native-flic2#17]
In the past I was having no issue with the library initiliazing itself, but all of a sudden when i call Flic2.isInitiailized() i seem to be getting back false. 

I don't really have any other information other then that.

**Comment by jdegger** [comment]
Hi, what version are you using? Have you recently upgraded or not? On what platform are you testing? We need more information to help you

**Comment by Dellybro** [comment]
Seems to have been a weird issue with react native itself while in development
