### ISSUE TITLE
Did not get disconnection of Flic button when it is not in range

### ISSUE THREAD

**Issue by Saurabh-Sawla** [X-Guard/react-native-flic2#24]
Dear programmer,

This is a wonderful support for the Flic library. However, we would like to understand how the button disconnection can be established when the Flic button is not in range and how it can be detected again. This is something that we could not get from the library.

Would you be able to add these capabilities to the library?

**Comment by jdegger** [comment]
Hi @Saurabh-Sawla we kindly redirect you question to the official Flic SDKs as this is not a question for us but for Shortcut Labs.

    Android: https://github.com/50ButtonsEach/flic2lib-android
    iOS: https://github.com/50ButtonsEach/flic2lib-ios

Search the issues on those repositories, it has been asked & answered before.

**Comment by Saurabh-Sawla** [comment]
Hi,

So I asked them this question and they say that there is a method that can help us get that status. please check this issue on the Android issue list - https://github.com/50ButtonsEach/flic2lib-android/issues/16

We could not find anything in the react native for this. Is it possible that same information can be obtained in react native.

Regards,
Saurabh

**Comment by jdegger** [comment]
Hi Saurabh,

Please check `Flic2Button.getIsReady();` and/or listen for the following events:

```
      Flic2.addListener('buttonConnectionReady', (eventData) => { console.log(eventData); });
      Flic2.addListener('buttonDisconnected', (eventData) => { console.log(eventData); }));
      Flic2.addListener('buttonConnectionCompleted',  (eventData) => { console.log(eventData); }));
```

**Comment by jdegger** [comment]
Please note that these events might trigger at unexpected times. For example, it will trigger when the button goes to sleep even though it's close and it won't connect until you trigger the button again.

**Comment by Saurabh-Sawla** [comment]
Alright thanks for this info, however, you mean these events may get triggered and provide a false positive. For example, a buttonDisconnected event may get fired even though in reality it isn't disconnected?

Regards,
Saurabh

**Comment by jdegger** [comment]
No, the button is really disconnected, but it doesn't mean that the button is out of reach and does not work.

- It really has disconnected
- However, this does not say anything about if the button will still work or is within reach or not

**Comment by Saurabh-Sawla** [comment]
Ok. That's fine we will try it out then. Thanks for all your help.
