### ISSUE TITLE
Getting exception on forgetAllButtons() method

### ISSUE THREAD

**Issue by Saurabh-Sawla** [X-Guard/react-native-flic2#25]
Dear Developer,

We are facing an issue on the react native flic library when we use forgetAllButtons() method. We have connected multiple devices to the application and when we perform a forgetAllButtons() method the application is crashing. 

The crash log gives "java.util.ConcurrentModificationException:" so it seems the list you are managing for devices is modifed from more than two threads at a time and the forgetAllButtons operation failed.

Kindly have a look and let us know how can this issue be fixed.

Regards,
Saurabh

**Comment by smartanimaltraining** [comment]
Thanks for the question!  I am very interested in the response.
Wes

**Comment by jdegger** [comment]
Hi, is `forgetButton` working for you?
