### ISSUE TITLE
Flic2 returns null

### ISSUE THREAD

**Issue by kejc** [X-Guard/react-native-flic2#26]
Hi, thank you for a great job. Though I am getting the following issue when deploying in a basic app deployed with expo.

```
TypeError: null is not an object (evaluating 'Flic2Module.registerFlic2ManagerInitializedCallback')
at node_modules/react-native/Libraries/Core/ExceptionsManager.js:104:6 in reportException
at node_modules/react-native/Libraries/Core/ExceptionsManager.js:171:19 in handleException
at node_modules/react-native/Libraries/Core/setUpErrorHandling.js:24:6 in handleError
at node_modules/expo-error-recovery/build/ErrorRecovery.fx.js:12:21 in ErrorUtils.setGlobalHandler$argument_0
at [native code]:null in flushedQueue
at [native code]:null in invokeCallbackAndReturnFlushedQueue
```

It is deployed to a device Lenovo Tab m10.
adb 31.0.2-7242960

Hope I have included enough information.

**Comment by jdegger** [comment]
Hi, I'm not entirely sure this works in Expo. This is a linking error, indicating that our plugin has not correctly been built.

Originally you have to execute the following command:

`$ npx react-native link react-native-flic2`

However, this method is outdated but we have not updated it yet to autolinking methods. You could try it but I'm not sure how it behaves in Expo and if it's possible. You might need to eject from expo.

**Comment by kejc** [comment]
Thank you so much for the quick reply, I will try it out :-)

**Comment by jdegger** [comment]
Closing this for now, let me know if any more assistance is needed.
