### ISSUE TITLE
Flic2 fails to work with `gradle 7.0.1`

### ISSUE THREAD

**Issue by punndcoder28** [X-Guard/react-native-flic2#28]
Flic2 fails to build with `gradle 7.0.1` mainly due to it still using `maven` which has been removed in the latest gradle. We cannot downgrade our gradle version since another dependency requires it to be the latest. Is there any workaround for this? Need to use this library for an important project integration. Any help from the developers would be appreciated. Thanks!

Edit 1: Adding the exact error message for better understanding
```
* What went wrong:
A problem occurred evaluating project ':react-native-flic2'.
> Plugin with id 'maven' not found.
```

**Comment by jdegger** [comment]
In the same changelog it says you can still use private maven repos (like jitpack as used by flic2)

https://docs.gradle.org/7.0/userguide/upgrading_version_6.html#jcenter_deprecation

If this is is really an issue, we need to escalate to the Flic team as they provide the library:

https://github.com/50ButtonsEach/flic2lib-android#flic2-lib-for-android

Also see last issue about this in the flic repo: https://github.com/50ButtonsEach/flic2lib-android/issues/17

**Comment by jdegger** [comment]
Are you on the newest version of react-native-flic2?

https://jitpack.io/#50ButtonsEach/flic2lib-android

Also has no mention of any changes to to syntax for any gradle version

**Comment by jdegger** [comment]
I think I understand the issue, however this is not an issue with our plugin but with the library. You might want to open an issue here (https://github.com/50ButtonsEach/flic2lib-android/issues). 

I still think it should not matter as the build is done by jitpack but I might be mistaken. 

You need react-native-flic2@0.3.18 at least

**Comment by punndcoder28** [comment]
Can you walk me through the process of changing it. I haven't done anything similar in the past

**Comment by LucasMonteiro1** [comment]
This issue is solved with https://github.com/X-Guard/react-native-flic2/pull/30

**Comment by MalikHassan512** [comment]
> Flic2 fails to build with `gradle 7.0.1` mainly due to it still using `maven` which has been removed in the latest gradle. We cannot downgrade our gradle version since another dependency requires it to be the latest. Is there any workaround for this? Need to use this library for an important project integration. Any help from the developers would be appreciated. Thanks!
> 
> Edit 1: Adding the exact error message for better understanding
> 
> ```
> * What went wrong:
> A problem occurred evaluating project ':react-native-flic2'.
> > Plugin with id 'maven' not found.
> ```

Add this line below of apply plugin: 'com.android.library'  this in react-native-flic2 build.gradle

`apply plugin: 'maven-publish'`

it will look like this 

```
apply plugin: 'com.android.library'
apply plugin: 'maven-publish'
```

**Comment by wesdewitte** [comment]
Try latest version
