### ISSUE TITLE
Circular Dependecies

### ISSUE THREAD

**Issue by punndcoder28** [X-Guard/react-native-flic2#33]
While going through the code for the package, I noticed that there is a circular dependency where `Flic` is imported in `FlicButton` which is in turn imported in `Flic`. Is this a necessary cycle? Can this be handled in a better manner? I would love to hear any suggestions and also contribute to solving this.

**Comment by jdegger** [comment]
We had the same problem in our main app. We recently resolved that by having the singletons defined as a global variable in de main index file. It's not ideal but removes the need for circular deps. If you have a better suggestion, it's also welcome of course. 👍

**Comment by wesdewitte** [comment]
Stale
