### ISSUE TITLE
react-native-flic2 not scanning a Flic2 button

### ISSUE THREAD

**Issue by MalikHassan512** [X-Guard/react-native-flic2#40]
Bluetooth is on
Location and Near By Devices permission is allow

Still not connected with the Flic2

**Comment by wesdewitte** [comment]
Are you on the latest version? And did you start the module with: Flic2.start()?

**Comment by MalikHassan512** [comment]
> Are you on the latest version? And did you start the module with: Flic2.start()?

Yes

**Comment by jdegger** [comment]
@MalikHassan512 Ik will close this issue for now as it is very old. Did you ever figure it out? If not, please check if the flic2 example app from shortcut labs themselves work for you.
