### ISSUE TITLE
Android 33 & RN 0.64 - Error "BLUETOOTH_SCAN/BLUETOOTH_CONNECT"

### ISSUE THREAD

**Issue by JB-CHAUVIN** [X-Guard/react-native-flic2#44]
I have the following error when trying to pair my button (crash) : 

BLUETOOTH_SCAN/BLUETOOTH_CONNECT not granted. Please call 'Activity.requestPermissions(String[], int') first.

Howewer I have granted coarsed and fine location already..

**Comment by JB-CHAUVIN** [comment]
Hello, anything new about my issue ?

**Comment by jdegger** [comment]
Did you request bluteooth permissions as well? Everything permissions related is not in our library. We chose to have that logic implemented by the developer. For example through react-native-permissions
