### ISSUE TITLE
Handle button click in background mode

### ISSUE THREAD

**Issue by maximko91** [X-Guard/react-native-flic2#47]
Hi @jdegger @wesdewitte . Thank for amazing lib. But I need your advice. Is there any possibility to handle button click when app in the background mode. Thanks for your reply.

**Comment by jdegger** [comment]
thanks! Should work fine out of the box. What is your setup like for it not to work?

**Comment by maximko91** [comment]
@jdegger I'm making a small research, to understand if this lib will work for me. My goal is to get events that button was clicked even when application in background and screen is locked. Thank you for your response.

**Comment by jdegger** [comment]
That will work fine on both iOS and Android. 👍
