### ISSUE TITLE
Location Permission Issue with react-native-flic2 Library on Android

### ISSUE THREAD

**Issue by JB-CHAUVIN** [X-Guard/react-native-flic2#48]
**Description:**
I am experiencing an issue with the react-native-flic2 library in my React Native project on Android. When I include the react-native-flic2 library and request location permissions, the app requests only approximate location of the device. However, when I do not include this library, the app requests precise & approximate location permission (desired behaviour).

**Steps to Reproduce:**

1. Create a new React Native project.
2. Add the react-native-flic2 library.
3. Request location permissions using a library like react-native-permissions or PermissionsAndroid.
4. Observe the permission request behavior on an Android 14 device (Samsung).

**Expected Behavior:**
The app should request the same location permissions regardless of whether the react-native-flic2 library is included or not.

**Actual Behavior:**
- With react-native-flic2 library: The app requests approximate location permission.
![IMG_2228-min](https://github.com/X-Guard/react-native-flic2/assets/8957878/87cfc61c-4b0b-4332-b26a-cdf36530b4fa)

- Without react-native-flic2 library: The app requests approximate **AND PRECISE** location permission.
![IMG_2229-min](https://github.com/X-Guard/react-native-flic2/assets/8957878/333a33c2-4632-43e1-8361-99ad0ec6c938)

**Environment:**
React Native version: 0.74.3
react-native-flic2 version:0.3.26
react-native-permissions: 4.1.5
Android version: Android 14
Device: Samsung 
Target Android SDK : 34

**Comment by jdegger** [comment]
I quickly googled this. It seems like we can avoid this by adding a declaration that we do not use the location when we scan Bluetooth. 

https://developer.android.com/develop/connectivity/bluetooth/bt-permissions

https://developer.android.com/develop/connectivity/bluetooth/bt-permissions#assert-never-for-location

I'm currently on my phone. Can you add this assertion in your app to see if that works? Otherwise we might need to change the package.

**Comment by JB-CHAUVIN** [comment]
<uses-permission android:name="android.permission.INTERNET" />
    <uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION" />
    <uses-permission android:name="android.permission.BLUETOOTH_SCAN" tools:remove="android:usesPermissionFlags" />
    <uses-permission android:name="android.permission.BLUETOOTH_CONNECT" />
    <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" tools:remove="maxSdkVersion" />

Fixed the issue !
