### ISSUE TITLE
fatal error: module 'flic2lib' not found

### ISSUE THREAD

**Issue by LeoCp** [X-Guard/react-native-flic2#9]
Build is failing in iOS

```
/Users/leonardo/my-security-v3/node_modules/react-native-flic2/ios/Flic2.h:8:9: fatal error: module 'flic2lib' not found
@import flic2lib;
 ~~~~~~~^~~~~~~~
6 warnings and 1 error generated.
```
@wesdewitte 
@jdegger

**Comment by wesdewitte** [comment]
@LeoCp Thx for the issue. The error has been noted, we are working on it. In the meantime you could go back to commit: 3107083ae9146322d31ecaf95ec7914b07e8e5ec
https://github.com/X-Guard/react-native-flic2/commit/3107083ae9146322d31ecaf95ec7914b07e8e5ec

After that we've updated the ios lib which is probably broken then.

**Comment by wesdewitte** [comment]
@LeoCp I've updated the package, tell me if the error is still there

**Comment by jdegger** [comment]
Closing this issue for now, let us know if it persists.
